### ISSUE TITLE
feature request: add support for FixedInstanceSize

### ISSUE THREAD

**Issue by ekle** [terraform-providers/terraform-provider-oneandone#4]
I started to add it myself (https://github.com/alfatraining/terraform-provider-oneandone), but there are many edge cases, i don't know how to handle, like:
- it is not possible to shrink FixedInstances
- it is not possible to increase memory from less than 4GB to 4GB without stopping the server

FixedInstances costs around the half than flexible servers. in most cases its cheaper to use a faster model of them, than using a individual sized server.

**Comment by jasminSPC** [comment]
@ekle Currently server resource has `ram`, `cores_per_processor`, `vcores` and `image` as required fields. If `FixedInstances` are added we'd need to do those checks. Also when it comes to update, like you said many edge cases would arise. But definitely it would be a good idea to add support for it. But if you already have done some work please submit your PR and we can work on it together. 

As for increasing memory can you please elaborate the use case.

**Comment by jasminSPC** [comment]
About increasing the memory there is a slight problem. 
When server is shut down and hardware update is performed (increasing RAM) we are not able to track server state since it is already `POWERED_OFF`. So we would not know how long to wait until the change is accepted and the server is ready to be `POWERED_ON`.

**Comment by ekle** [comment]
@jasminSPC here: https://github.com/terraform-providers/terraform-provider-oneandone/pull/5 it is based on your fork at the moment.

**Comment by jasminSPC** [comment]
@ekle thanks I'm looking at it.

**Comment by jasminSPC** [comment]
Fixed with #5
