### ISSUE TITLE
oneandone_server resource not recreated on image change

### ISSUE THREAD

**Issue by arminbuerkle** [terraform-providers/terraform-provider-oneandone#8]
## Terraform Version
`Terraform v0.10.2`

### Affected Resource(s)
- oneandone_server

### Expected Behavior
VM should be destroyed and recreated with the new image.

### Actual Behavior
`terraform.tfstate` file is updated but the remote resource hasn't changed.

### Steps to Reproduce
1. Create any `oneandone_server` with any image. I used a "debian8-64min".
2. Change the image. For example to "debian9-64min".
3. `terraform plan` will output it as a change but doesn't want to recreate the resource
```
  ~ module.oneandone_media_de.module.audio.oneandone_server.main
      image: "debian8-64min" => "debian9-64min"
```
4. `terraform apply` will succeed and update the `.tfstate` file
5. Next `terraform plan` will output 'No changes'.

**Comment by jasmingacic** [comment]
Fixed with #11 
@arminbuerkle Thank you for reporting this bug. It will be released with v1.0.0 of the provider.
